title: your awesome title
description: your web description
keywords: 'your web keywords, another keywords'
url: ''
nav:
  首页: /
  标签: /tags.html
  时间线: /timeline.html
  关于博主: /about.html
  友情链接: /friendLink.html
author: true
name: your awesome name
NickName: your awesome nickname
webtitle: your awesome webtitle
bio: your awesome bio
about: true
aboutyou: your introduction
portraits: /assets/profile.jpeg
SNS: true
SNS-icon:
  mail: 'mailto:abc@gmail.com'
  weixin: ''
  qq: ''
  github: ''
  Codepen: ''
  weibo: ''
  instagram: ''
  Twitter: ''
  Dribbble: ''
  Facebook: ''
  Google: ''
  zhihu: ''
  juejin: ''
  twitch: ''
paginate: 2
paginatepath:
  - 'page:num'
footer:
  since: 2018
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
pygmentsTheme: default
friends:
  jekyll: 'https://www.jekyll.com.cn/'
disqus: false
disqus_url: ''
livere: true
livere_uid: MTAyMC8zNDI2OS8xMDgwNg==
Gitment: false
Gitment_owner: ''
Gitment_repo: ''
client_id: ''
client_secret: ''
social-share: true
social-share-items:
  - qq
  - wechat
  - weibo
  - twitter
  - facebook
baidu: true
baidu-url: ''
google: false
google-ID: ''
color: 'rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)'
baseurl: ''
